<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>demo-project</artifactId>
    <version>2.3-SNAPSHOT</version>
    <packaging>jar</packaging>

   <!--
    <packaging>pom</packaging>
     <modules>
        <module>agent-installer</module>
        &lt;!&ndash;<module>demo-jar</module>&ndash;&gt;
    </modules>-->

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>
    <distributionManagement>
        <repository>
            <id>l3c-auto11-10.49.29.133-repo</id>
            <url>http://10.49.29.133:8081/repository/GuestRepo/</url>
        </repository>
    </distributionManagement>
</project>